global:
  scrape_interval: 1s

scrape_configs:
  - job_name: zookeeper
    static_configs:
      - targets:
          - zookeeper:7071
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: kafka
    static_configs:
      - targets:
        - broker-1:7071
        - broker-2:7071
        - broker-3:7071
        - broker-4:7071
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: kafka-sr
    static_configs:
      - targets:
          - schema-registry:7071
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: kafka_exporter
    static_configs:
      - targets:
        - kafka-exporter:9308
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
  - job_name: targets
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '$1'
